blog/api/urls.py
from django.urls import path

from blog.api import views


urlpatterns = [
    path('posts/for/all', views.PostForAllListApiView.as_view(), name='api_posts_for_all'),
    path('posts/subscriptions', views.PostSubscriptionsListApiView.as_view(), name='api_posts_subscriptions'),
    path('posts/my/all', views.PostMyAllListApiView.as_view(), name='api_posts_my_all'),
    path('posts/my/drafts', views.PostMyDraftsListApiView.as_view(), name='api_posts_my_drafts'),
    path('posts/my/for/all', views.PostMyForAllListApiView.as_view(), name='api_posts_my_for_all'),
    path('posts/my/for/subscribers', views.PostMyForSubscribersListApiView.as_view(), name='api_posts_my_for_subscribers'),
    path('posts/post/<str:slug>', views.PostApiView.as_view(), name='post_api_view'),
]

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.posts, name="posts"),
    path("posts", views.posts, name="posts"),
    path("posts/view/<param>", views.posts, name="posts"),

    path("posts/post/create", views.post_create, name="post_create"),
    path("posts/post/view/<slug>", views.post_view, name="post_view"),
    path("posts/post/edit/<slug>", views.post_edit, name="post_edit"),
    path("posts/post/delete/<slug>", views.post_delete, name="post_delete"),
    path("posts/post/comment/add/<slug>", views.post_add_comment, name="post_add_comment"),
    path("posts/post/comment/delete/<int:comment_id>", views.post_delete_comment, name="post_delete_comment"),
    path("posts/post/status/change/<slug>/<param>", views.post_status_change, name="post_status_change"),

    path("like/<obj>/<int:object_id>", views.toggle_like, name="toggle_like"),

    path("rate/post/<int:post_id>", views.rate_post, name="rate_post"),

    path("search_in_my_posts", views.search_in_my_posts, name="search_in_my_posts"),
    path("search_publish_posts", views.search_publish_posts, name="search_publish_posts"),

    path("auth/signin", views.user_signin, name="user_signin"),
    path("accounts/login/", views.user_signin, name="user_signin"),
    path("auth/signup", views.user_signup, name="user_signup"),
    path("auth/logout", views.user_logout, name="user_logout"),

    path("user/profile/<int:user_id>", views.user_profile, name="user_profile"),
    path("user/bio/update", views.user_bio_update, name="user_bio_update"),
    path("user/email/update", views.user_email_update, name="user_email_update"),
    path("user/names/update", views.user_names_update, name="user_names_update"),
    path("user/password/update", views.user_password_update, name="user_password_update"),
    path("user/sub_unsub_scribe/<int:user_id>", views.user_sub_unsub_scribe, name="user_sub_unsub_scribe"),
]

tipsetc/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("api/", include("blog.api.urls")),
]

blog/models/comment.py
from django.contrib.auth.models import User
from django.db import models

from .mixins import CreatedAtMixin

class Comment(
    CreatedAtMixin,
    models.Model
):
    content = models.TextField(
        null=False,
        blank=False,
    )

    post = models.ForeignKey(
        "Post",
        on_delete=models.CASCADE,
        related_name="comments",
        null=False,
    )

    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="comments",
        null=True,
    )

    class Meta:
        db_table = "comments"

    @property
    def likes_count(self) -> int:
        return self.likes.count()

    def is_liked_by(self, user: User) -> bool:
        return self.likes.filter(user=user).exists()

blog/models/like.py
from django.contrib.auth.models import User
from django.db import models

from .comment import Comment
from .post import Post
from .mixins import CreatedAtMixin


class PostLike(
    CreatedAtMixin,
    models.Model,
):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="likes",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="posts_likes",
        null=True,
    )

    class Meta:
        db_table = "posts_likes"
        unique_together = ("post", "user")


class CommentLike(
    CreatedAtMixin,
    models.Model,
):
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        related_name="likes",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="comments_likes",
        null=True,
    )

    class Meta:
        db_table = "comments_likes"
        unique_together = ("comment", "user")

blog/models/mixins.py
from django.db import models


class CreatedAtMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class UpdatedAtMixin(models.Model):
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

blog/models/post.py
from django.db import models

from . import mixins
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(
    mixins.CreatedAtMixin,
    mixins.UpdatedAtMixin,
    models.Model,
):
    PUBLISH_STATUS = [
        ("draft", "Draft"),
        ("for_subscribers", "Published for subscribers"),
        ("for_all", "Published for All"),
    ]
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, allow_unicode=True, null=True, blank=True)
    content = models.TextField(db_index=True, null=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="posts"
    )
    published = models.CharField(max_length=16, choices=PUBLISH_STATUS, null=False)

    tags = models.ManyToManyField("Tag", related_name="posts", blank=True)

    rating = models.PositiveIntegerField(null=False, default=0)
    ratings_count = models.PositiveIntegerField(null=False, default=0)

    class Meta:
        db_table = "posts"

    def __str__(self):
        return self.title

    @property
    def published_status(self):
        post_publish_status = {x[0]: x[1] for x in self.PUBLISH_STATUS}
        return post_publish_status[str(self.published)]

    @property
    def likes_count(self) -> int:
        return self.likes.count()

    def is_liked_by(self, user: User) -> bool:
        return self.likes.filter(user=user).exists()

    @property
    def ratings(self) -> float | None:
        if self.ratings_count == 0:
            ratings = None
            return ratings
        else:
            ratings = self.rating / self.ratings_count
            return ratings

blog/models/signals.py
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver

from .user_profile import UserProfile


@receiver(post_save, sender=User)
def create_or_update_user_profile(
    sender: type[User], instance: User, created: bool, **kwargs
):
    if created:
        UserProfile.objects.create(user=instance)
    else:
        instance.profile.save()

blog/forms/post.py
from django import forms

from blog.models import Post


class CreateEditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'content', 'published']

blog/forms/user.py
from django import forms
from django.contrib.auth import get_user_model

from blog.models import UserProfile


User = get_user_model()

class UserNamesForm(forms.Form):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username']

class UserEmailForm(forms.Form):
    class Meta:
        model = User
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

class UserPasswordForm(forms.Form):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']
        widgets = {
            'old_password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password2': forms.PasswordInput(attrs={'class': 'form-control'}),

        }

class UserBioForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio']

blog/api/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q

from rest_framework import generics, permissions

from blog.api.serializers import PostSerializer
from blog.models import Post, Subscription, UserProfile

User = get_user_model()


class PostForAllListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    def get_queryset(self):
        return Post.objects.filter(published="for_all").all()


class PostSubscriptionsListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return None
        subscriptions = Subscription.objects.filter(subscriber=self.request.user.profile).all()
        subscribed_to = [i.subscribed_to.user.username for i in subscriptions]
        return Post.objects.filter(author__username__in=subscribed_to).filter(published="for_subscribers")


class PostMyAllListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).all()


class PostMyDraftsListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).filter(published="draft").all()


class PostMyForAllListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).filter(published="for_all").all()


class PostMyForSubscribersListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).filter(published="for_subscribers").all()


class PostApiView(generics.RetrieveAPIView):
    serializer_class = PostSerializer
    lookup_field = 'slug'

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            queryset = Post.objects.filter(published="for_all").all()
        else:
            post = Post.objects.get(slug=self.kwargs['slug'])
            if post.published == "for_all" or post.author == self.request.user:
                queryset = Post.objects.filter(
                    Q(published="for_all") |
                    Q(author=self.request.user)
                ).all()
            elif post.published == "for_subscribers" and Subscription.objects.filter(subscriber=self.request.user.profile, subscribed_to=UserProfile.objects.get(user=User.objects.get(id=post.author.id))).exists():
                queryset = Post.objects.filter(published="for_subscribers").all()
            else:
                queryset = Post.objects.filter(published="for_all").all()
        return queryset

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models.query_utils import Q
from django.shortcuts import get_object_or_404, render
from django.conf import settings

from .models import Post


# Create your views here.

def posts(request, param=""):
    params = {
        "": Post.objects.filter(published="for_all"),
        "all_publish_posts": Post.objects.filter(published="for_all"),
        "exception": Post.objects.filter(published="for_all"),
    }
    titles = {
        "": "Latest Published Posts",
        "all_publish_posts": "Latest Published Posts",
        "exception": f"This page \"{param}\" does not exist. Below are latest Published Posts.",
    }

    if request.user.is_authenticated:
        params["my_posts"] = Post.objects.filter(author=request.user)
        titles["my_posts"] = "My Posts"
    if not param in params:
        param = "exception"
    # q_posts = params[param].order_by("-updated_at")[:settings.COUNT_OF_POST_ON_PAGE]
    q_posts = params[param].order_by("-updated_at")

    page_number = request.GET.get('page', 1)
    paginator = Paginator(q_posts, settings.COUNT_OF_POST_ON_PAGE)
    page_obj = paginator.get_page(page_number)

    title = titles[param]
    context = {
        "posts": page_obj,
        "count_posts": q_posts.count(),
        "settings": settings,
        "title": title,
        "param": param,
        "has_next": page_obj.has_next(),
        "next_page": page_obj.next_page_number() if page_obj.has_next() else None,
    }

    # if request.headers.get("HX-Request") is True:
    if page_number == 1:
        return render(request, "post/posts.html", context)

    return render(request, "post/blocks/posts_item.html", context)


def search_publish_posts(request):
    query = request.GET.get('query')
    results = []
    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query)).order_by("-updated_at")[:settings.SEARCH_RESULTS_LIMIT]

    return render(
        request,
        "post/blocks/search_publish_posts.html",
        {"results": results, "query": query},
    )

def post_view(request, slug):
    result = get_object_or_404(Post, slug=slug)
    context = {
        "post": result,
        "settings": settings,
    }
    return render(request, "post/post.html", context)

blog/views/comment.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render

from blog.models import Comment, Post


@login_required
def post_add_comment(request, slug: str):
    if request.method != "POST":
        return HttpResponseBadRequest()

    post = get_object_or_404(Post, slug=slug)
    user = request.user
    content = request.POST.get("content")
    if not (content := content.strip()):
        return HttpResponseBadRequest()

    Comment.objects.create(content=content, user=user, post=post)

    context = {
        "comments": Comment.objects.filter(post=post).all(),
    }

    return render(request, "post/blocks/comments_list.html", context)

@login_required
def post_delete_comment(request, comment_id: int):
    if request.method != "POST":
        return HttpResponseBadRequest()

    comment = get_object_or_404(Comment, id=comment_id)
    post = get_object_or_404(Post, id=comment.post.id)
    user = request.user
    if comment.user == user:
        comment.delete()

        context = {
            "comments": post.comments.all(),
        }

        return render(request, "post/blocks/comments_list.html", context)

    else:
        return HttpResponseBadRequest()

blog/views/like.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render

from blog.models import Post, PostLike, Comment, CommentLike


@login_required
def toggle_like(request, obj, object_id: int):
    if request.method != 'POST':
        return HttpResponseBadRequest()

    if obj == "post":
        object_like = get_object_or_404(Post, id=object_id)
        like, created = PostLike.objects.get_or_create(user=request.user, post=object_like)

    elif obj == "comment":
        object_like = get_object_or_404(Comment, id=object_id)
        like, created = CommentLike.objects.get_or_create(user=request.user, comment=object_like)

    if not created:
        like.delete()

    context = {
        "comment": object_like,
        "post": object_like,
    }

    return render(request, f'post/blocks/{obj}_like_button.html', context)

blog/views/rating.py
from blog.models import Post, PostRating

from django import shortcuts
from django.contrib.auth.decorators import login_required

from blog.tasks.posts import update_post_rating_again, update_post_rating_new


@login_required
def rate_post(request, post_id):
    post = shortcuts.get_object_or_404(Post, id=post_id)
    if not PostRating.objects.filter(post=post, user=request.user).exists():
        users_rating = 0
    else:
        post_rating = PostRating.objects.filter(post=post, user=request.user).first()
        users_rating = old_rating = post_rating.rating

    if request.method == "POST":
        rating = int(request.POST.get("rate"))

        if not PostRating.objects.filter(post=post, user=request.user).exists():
            post_rating, created = PostRating.objects.get_or_create(user=request.user, post=post, rating=rating)
            update_post_rating_new.delay(post_id=post.id, rating=rating)
            post_rating.save()
        else:
            update_post_rating_again.delay(post_id=post.id, old_rating=old_rating, rating=rating)
            post_rating.rating = rating
            post_rating.save()

        users_rating = rating

    context = {
        "post": post,
        "users_rating": users_rating,
    }

    return shortcuts.render(request, "post/blocks/post_rate.html", context)

blog/templates/post/post.html
{% extends "main/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div class="col-lg-8 mx-auto p-4 py-md-5">
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        {% load static %}
        <p style="max-width:30%; height: auto;">
            <img src="{% static 'logo/logo_max.png' %}" class="img-fluid" alt="Tips etc.. Logos.">
        </p>
        <h1 style="max-width:70%; height: auto;">{{ post.title }}</h1>
    </header>
    {% include 'post/blocks/post_info.html' %}

    <main>

        <div class="d-flex flex-wrap align-items-center justify-content-between">
            <p>
                {{ post.content }}
            </p>
        </div>
        <hr class="mt-5 mb-5">

    </main>

</div>

{% endblock %}

blog/templates/post/post_create.html
{% extends "main/base.html" %}

{% block title %}Create new post{% endblock %}

{% block content %}

<div class="col-lg-6 mx-auto p-4 py-md-5">
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        {% load static %}
        <p style="max-width:30%; height: auto;">
            <img src="{% static 'logo/logo_max.png' %}" class="img-fluid" alt="Tips etc.. Logos.">
        </p>
        <h1 style="max-width:70%; height: auto;">Create new post</h1>
    </header>
    <main class="w-100 m-auto">
        <form method="POST" action="{% url 'post_create' %}">
            {% csrf_token %}
            <div class="form-floating">
                <input
                        type="text"
                        class="form-control"
                        id="id_title"
                        name="title"
                        placeholder="Post title"
                        required
                >
                <label for="id_title">Post title:</label>
            </div>
            <div class="form-floating mt-3">
                <input
                        type="text"
                        class="form-control"
                        id="id_slug"
                        name="slug"
                        placeholder="Post slug"
                >
                <label for="id_slug">Post slug:</label>
            </div>
            <div class="form-group mt-3">
                <label for="id_content" class="text-body-secondary">Post content:</label>
                <textarea
                        class="form-control"
                        id="id_content"
                        name="content"
                        rows="5"
                        placeholder="Post content"
                ></textarea>
            </div>
            <div class="form-floating mt-3">
                <select
                        class="form-control"
                        id="id_published"
                        name="published"
                        required
                >
                    <option value selected>-- Please make your choice --</option>
                    <option value="draft">Draft</option>
                    <option value="for_subscribers">Published for subscribers</option>
                    <option value="for_all">Published for All</option>
                </select>
                <label for="id_published" class="text-body-secondary">Publish status:</label>
            </div>

            <button class="btn btn-secondary w-100 py-2 mt-4" type="submit">Post</button>

        </form>
        <hr class="mt-5 mb-5">
    </main>
</div>

{% endblock %}

blog/templates/post/post_edit.html
{% extends "main/base.html" %}

{% block title %}Edit post: {{ post.title }}{% endblock %}

{% block content %}

<div class="col-lg-6 mx-auto p-4 py-md-5">
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        {% load static %}
        <p style="max-width:30%; height: auto;">
            <img src="{% static 'logo/logo_max.png' %}" class="img-fluid" alt="Tips etc.. Logos.">
        </p>
        <h1 style="max-width:70%; height: auto;">Edit post: {{ post.title }}</h1>
    </header>
    <main class="w-100 m-auto">
        <form method="POST" action="{% url 'post_edit' slug=post.slug %}" class="was-validated">
            {% csrf_token %}
            <div class="form-floating">
                <input
                        type="text"
                        class="form-control is-invalid"
                        id="id_title"
                        name="title"
                        placeholder="Post title"
                        value="{{ post.title }}"
                        required
                >
                <label for="id_title">Post title:</label>

            </div>
            <div class="form-group mt-3">
                <label for="id_content" class="text-body-secondary">Post content:</label>
                <textarea
                        class="form-control is-invalid"
                        id="id_content"
                        name="content"
                        rows="5"
                        placeholder="Post content"
                >{{ post.content }}</textarea>
            </div>
            <div class="form-floating mt-3">
                <select
                        class="form-control is-invalid"
                        id="id_published"
                        name="published"
                        aria-selected="{{ post.published }}"
                        required
                >
                    <option value selected>-- Please make your choice --</option>
                    {% for i in post.PUBLISH_STATUS %}
                    {% if post.published == i.0 %}
                    <option selected value="{{ i.0 }}">{{ i.1 }}</option>
                    {% else %}
                    <option value="{{ i.0 }}">{{ i.1 }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <label for="id_published" class="text-body-secondary">Publish status:</label>
            </div>

            <button class="btn btn-outline-success w-100 py-2 mt-4" type="submit">Save changes</button>

        </form>
        <hr class="mt-5 mb-5">
    </main>
</div>

{% endblock %}

blog/templates/post/post_view.html
{% extends "main/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div class="col-lg-8 mx-auto p-4 py-md-5">
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        {% load static %}
        <p style="max-width:30%; height: auto;">
            <img src="{% static 'logo/logo_max.png' %}" class="img-fluid" alt="Tips etc.. Logos.">
        </p>
        <h1 style="max-width:70%; height: auto;">{{ post.title }}</h1>
    </header>
    {% include 'post/blocks/post_info_view.html' %}

    <main>

        <div class="d-flex flex-wrap justify-content-between">
            <p>
                {{ post.content }}
            </p>
        </div>

        <div class="d-flex justify-content-between">
            {% include "post/blocks/post_like_button.html" %}
            {% include "post/blocks/post_rate.html" %}
        </div>




        <hr class="mt-5 mb-5">
        <div id="comments-block" class="mt-4">
            <h3>Comments</h3>
            <br>
            {% if request.user.is_authenticated %}
                <form
                    id="form-comment"
                    hx-post="{% url 'post_add_comment' slug=post.slug %}"
                    hx-target="#comments-list"
                    swap="outerHTML"
                    class="mb-3"
                >
                    {% csrf_token %}
                    <textarea
                        id="form-comment-textarea"
                        name="content"
                        rows="3"
                        class="form-control"
                        placeholder="Write a comment..."
                    ></textarea>
                    <button
                        id="form-comment-submit"
                        class="btn btn-outline-secondary mt-2"
                        type="submit"
                    >
                        Add Comment
                    </button>
                </form>
            {% else %}
                <p>
                    <a
                        class="link-body-emphasis link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                        href="{% url 'user_signin' %}"
                    >
                        Sign in
                    </a> or <a
                        class="link-body-emphasis link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                        href="{% url 'user_signup' %}"
                    >
                        Sign up
                    </a> to comment.
                </p>
            {% endif %}
            <div id="comments-list">
                {% include "post/blocks/comments_list.html" with comments=post.comments.all  %}
            </div>
        </div>

    </main>

</div>

<script>
    const formComment = document.getElementById("form-comment")
    const formCommentBtn = document.getElementById("form-comment-submit")

    formCommentBtn.addEventListener("click", () => {
        setTimeout(function () {
            formComment.reset()
        }, 200)
    });
</script>

{% endblock %}

blog/templates/post/posts.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="col-lg-8 mx-auto p-4 py-md-5">

    {% if request.user.is_authenticated %}
    {% if param == 'my_posts' or param == 'my_drafts' or param == 'my_posts_for_all' or param == 'my_posts_for_subscribers' %}
    {% include "post/blocks/posts_tabs.html"%}
    {% endif %}
    {% endif %}

    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        {% load static %}
        <p style="max-width:50%; height: auto;">
            <img src="{% static 'logo/logo_max.png' %}" class="img-fluid" alt="Tips etc.. Logos.">
        </p>
        <h1 style="max-width: 50%; height: auto;">
            {{ title }}
            ({{ count_posts }})
        </h1>
    </header>

    {% include "post/blocks/posts_item.html"%}

</div>

{% endblock %}