blog/api/urls.py
from django.urls import path

from blog.api import views


urlpatterns = [
    path('posts/for/all', views.PostForAllListApiView.as_view(), name='api_posts_for_all'),
    path('posts/subscriptions', views.PostSubscriptionsListApiView.as_view(), name='api_posts_subscriptions'),
    path('posts/my/all', views.PostMyAllListApiView.as_view(), name='api_posts_my_all'),
    path('posts/my/drafts', views.PostMyDraftsListApiView.as_view(), name='api_posts_my_drafts'),
    path('posts/my/for/all', views.PostMyForAllListApiView.as_view(), name='api_posts_my_for_all'),
    path('posts/my/for/subscribers', views.PostMyForSubscribersListApiView.as_view(), name='api_posts_my_for_subscribers'),
    path('posts/post/<str:slug>', views.PostApiView.as_view(), name='post_api_view'),
]

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.posts, name="posts"),
    path("posts", views.posts, name="posts"),
    path("posts/view/<param>", views.posts, name="posts"),

    path("posts/post/create", views.post_create, name="post_create"),
    path("posts/post/view/<slug>", views.post_view, name="post_view"),
    path("posts/post/edit/<slug>", views.post_edit, name="post_edit"),
    path("posts/post/delete/<slug>", views.post_delete, name="post_delete"),
    path("posts/post/comment/add/<slug>", views.post_add_comment, name="post_add_comment"),
    path("posts/post/comment/delete/<int:comment_id>", views.post_delete_comment, name="post_delete_comment"),
    path("posts/post/status/change/<slug>/<param>", views.post_status_change, name="post_status_change"),

    path("like/<obj>/<int:object_id>", views.toggle_like, name="toggle_like"),

    path("rate/post/<int:post_id>", views.rate_post, name="rate_post"),

    path("search_in_my_posts", views.search_in_my_posts, name="search_in_my_posts"),
    path("search_publish_posts", views.search_publish_posts, name="search_publish_posts"),

    path("auth/signin", views.user_signin, name="user_signin"),
    path("accounts/login/", views.user_signin, name="user_signin"),
    path("auth/signup", views.user_signup, name="user_signup"),
    path("auth/logout", views.user_logout, name="user_logout"),

    path("user/profile/<int:user_id>", views.user_profile, name="user_profile"),
    path("user/bio/update", views.user_bio_update, name="user_bio_update"),
    path("user/email/update", views.user_email_update, name="user_email_update"),
    path("user/names/update", views.user_names_update, name="user_names_update"),
    path("user/password/update", views.user_password_update, name="user_password_update"),
    path("user/sub_unsub_scribe/<int:user_id>", views.user_sub_unsub_scribe, name="user_sub_unsub_scribe"),
]

tipsetc/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("api/", include("blog.api.urls")),
]

blog/models/comment.py
from django.contrib.auth.models import User
from django.db import models

from .mixins import CreatedAtMixin

class Comment(
    CreatedAtMixin,
    models.Model
):
    content = models.TextField(
        null=False,
        blank=False,
    )

    post = models.ForeignKey(
        "Post",
        on_delete=models.CASCADE,
        related_name="comments",
        null=False,
    )

    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="comments",
        null=True,
    )

    class Meta:
        db_table = "comments"

    @property
    def likes_count(self) -> int:
        return self.likes.count()

    def is_liked_by(self, user: User) -> bool:
        return self.likes.filter(user=user).exists()

blog/models/like.py
from django.contrib.auth.models import User
from django.db import models

from .comment import Comment
from .post import Post
from .mixins import CreatedAtMixin


class PostLike(
    CreatedAtMixin,
    models.Model,
):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="likes",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="posts_likes",
        null=True,
    )

    class Meta:
        db_table = "posts_likes"
        unique_together = ("post", "user")


class CommentLike(
    CreatedAtMixin,
    models.Model,
):
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        related_name="likes",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="comments_likes",
        null=True,
    )

    class Meta:
        db_table = "comments_likes"
        unique_together = ("comment", "user")

blog/models/mixins.py
from django.db import models


class CreatedAtMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class UpdatedAtMixin(models.Model):
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

blog/models/post.py
from django.db import models

from . import mixins
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(
    mixins.CreatedAtMixin,
    mixins.UpdatedAtMixin,
    models.Model,
):
    PUBLISH_STATUS = [
        ("draft", "Draft"),
        ("for_subscribers", "Published for subscribers"),
        ("for_all", "Published for All"),
    ]
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, allow_unicode=True, null=True, blank=True)
    content = models.TextField(db_index=True, null=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="posts"
    )
    published = models.CharField(max_length=16, choices=PUBLISH_STATUS, null=False)

    tags = models.ManyToManyField("Tag", related_name="posts", blank=True)

    rating = models.PositiveIntegerField(null=False, default=0)
    ratings_count = models.PositiveIntegerField(null=False, default=0)

    class Meta:
        db_table = "posts"

    def __str__(self):
        return self.title

    @property
    def published_status(self):
        post_publish_status = {x[0]: x[1] for x in self.PUBLISH_STATUS}
        return post_publish_status[str(self.published)]

    @property
    def likes_count(self) -> int:
        return self.likes.count()

    def is_liked_by(self, user: User) -> bool:
        return self.likes.filter(user=user).exists()

    @property
    def ratings(self) -> float | None:
        if self.ratings_count == 0:
            ratings = None
            return ratings
        else:
            ratings = self.rating / self.ratings_count
            return ratings

blog/models/user_profile.py
from django.contrib.auth import get_user_model
from django.db import models

from . import mixins

User = get_user_model()


class UserProfile(mixins.CreatedAtMixin, mixins.UpdatedAtMixin, models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    bio = models.TextField(max_length=500, null=True, blank=True)
    avatar = models.URLField(null=True, blank=True)

    class Meta:
        db_table = "user_profiles"

    def __str__(self):
        return f"{self.user.username}'s profile"

blog/forms/post.py
from django import forms

from blog.models import Post


class CreateEditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'content', 'published']

blog/forms/user.py
from django import forms
from django.contrib.auth import get_user_model

from blog.models import UserProfile


User = get_user_model()

class UserNamesForm(forms.Form):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username']

class UserEmailForm(forms.Form):
    class Meta:
        model = User
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

class UserPasswordForm(forms.Form):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']
        widgets = {
            'old_password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password2': forms.PasswordInput(attrs={'class': 'form-control'}),

        }

class UserBioForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio']

blog/api/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q

from rest_framework import generics, permissions

from blog.api.serializers import PostSerializer
from blog.models import Post, Subscription, UserProfile

User = get_user_model()


class PostForAllListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    def get_queryset(self):
        return Post.objects.filter(published="for_all").all()


class PostSubscriptionsListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return None
        subscriptions = Subscription.objects.filter(subscriber=self.request.user.profile).all()
        subscribed_to = [i.subscribed_to.user.username for i in subscriptions]
        return Post.objects.filter(author__username__in=subscribed_to).filter(published="for_subscribers")


class PostMyAllListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).all()


class PostMyDraftsListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).filter(published="draft").all()


class PostMyForAllListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).filter(published="for_all").all()


class PostMyForSubscribersListApiView(generics.ListAPIView):
    serializer_class = PostSerializer

    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).filter(published="for_subscribers").all()


class PostApiView(generics.RetrieveAPIView):
    serializer_class = PostSerializer
    lookup_field = 'slug'

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            queryset = Post.objects.filter(published="for_all").all()
        else:
            post = Post.objects.get(slug=self.kwargs['slug'])
            if post.published == "for_all" or post.author == self.request.user:
                queryset = Post.objects.filter(
                    Q(published="for_all") |
                    Q(author=self.request.user)
                ).all()
            elif post.published == "for_subscribers" and Subscription.objects.filter(subscriber=self.request.user.profile, subscribed_to=UserProfile.objects.get(user=User.objects.get(id=post.author.id))).exists():
                queryset = Post.objects.filter(published="for_subscribers").all()
            else:
                queryset = Post.objects.filter(published="for_all").all()
        return queryset

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models.query_utils import Q
from django.shortcuts import get_object_or_404, render
from django.conf import settings

from .models import Post


# Create your views here.

def posts(request, param=""):
    params = {
        "": Post.objects.filter(published="for_all"),
        "all_publish_posts": Post.objects.filter(published="for_all"),
        "exception": Post.objects.filter(published="for_all"),
    }
    titles = {
        "": "Latest Published Posts",
        "all_publish_posts": "Latest Published Posts",
        "exception": f"This page \"{param}\" does not exist. Below are latest Published Posts.",
    }

    if request.user.is_authenticated:
        params["my_posts"] = Post.objects.filter(author=request.user)
        titles["my_posts"] = "My Posts"
    if not param in params:
        param = "exception"
    # q_posts = params[param].order_by("-updated_at")[:settings.COUNT_OF_POST_ON_PAGE]
    q_posts = params[param].order_by("-updated_at")

    page_number = request.GET.get('page', 1)
    paginator = Paginator(q_posts, settings.COUNT_OF_POST_ON_PAGE)
    page_obj = paginator.get_page(page_number)

    title = titles[param]
    context = {
        "posts": page_obj,
        "count_posts": q_posts.count(),
        "settings": settings,
        "title": title,
        "param": param,
        "has_next": page_obj.has_next(),
        "next_page": page_obj.next_page_number() if page_obj.has_next() else None,
    }

    # if request.headers.get("HX-Request") is True:
    if page_number == 1:
        return render(request, "post/posts.html", context)

    return render(request, "post/blocks/posts_item.html", context)


def search_publish_posts(request):
    query = request.GET.get('query')
    results = []
    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query)).order_by("-updated_at")[:settings.SEARCH_RESULTS_LIMIT]

    return render(
        request,
        "post/blocks/search_publish_posts.html",
        {"results": results, "query": query},
    )

def post_view(request, slug):
    result = get_object_or_404(Post, slug=slug)
    context = {
        "post": result,
        "settings": settings,
    }
    return render(request, "post/post.html", context)

blog/views/comment.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render

from blog.models import Comment, Post


@login_required
def post_add_comment(request, slug: str):
    if request.method != "POST":
        return HttpResponseBadRequest()

    post = get_object_or_404(Post, slug=slug)
    user = request.user
    content = request.POST.get("content")
    if not (content := content.strip()):
        return HttpResponseBadRequest()

    Comment.objects.create(content=content, user=user, post=post)

    context = {
        "comments": Comment.objects.filter(post=post).all(),
    }

    return render(request, "post/blocks/comments_list.html", context)

@login_required
def post_delete_comment(request, comment_id: int):
    if request.method != "POST":
        return HttpResponseBadRequest()

    comment = get_object_or_404(Comment, id=comment_id)
    post = get_object_or_404(Post, id=comment.post.id)
    user = request.user
    if comment.user == user:
        comment.delete()

        context = {
            "comments": post.comments.all(),
        }

        return render(request, "post/blocks/comments_list.html", context)

    else:
        return HttpResponseBadRequest()

blog/views/like.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render

from blog.models import Post, PostLike, Comment, CommentLike


@login_required
def toggle_like(request, obj, object_id: int):
    if request.method != 'POST':
        return HttpResponseBadRequest()

    if obj == "post":
        object_like = get_object_or_404(Post, id=object_id)
        like, created = PostLike.objects.get_or_create(user=request.user, post=object_like)

    elif obj == "comment":
        object_like = get_object_or_404(Comment, id=object_id)
        like, created = CommentLike.objects.get_or_create(user=request.user, comment=object_like)

    if not created:
        like.delete()

    context = {
        "comment": object_like,
        "post": object_like,
    }

    return render(request, f'post/blocks/{obj}_like_button.html', context)

blog/views/rating.py
from blog.models import Post, PostRating

from django import shortcuts
from django.contrib.auth.decorators import login_required

from blog.tasks.posts import update_post_rating_again, update_post_rating_new


@login_required
def rate_post(request, post_id):
    post = shortcuts.get_object_or_404(Post, id=post_id)
    if not PostRating.objects.filter(post=post, user=request.user).exists():
        users_rating = 0
    else:
        post_rating = PostRating.objects.filter(post=post, user=request.user).first()
        users_rating = old_rating = post_rating.rating

    if request.method == "POST":
        rating = int(request.POST.get("rate"))

        if not PostRating.objects.filter(post=post, user=request.user).exists():
            post_rating, created = PostRating.objects.get_or_create(user=request.user, post=post, rating=rating)
            update_post_rating_new.delay(post_id=post.id, rating=rating)
            post_rating.save()
        else:
            update_post_rating_again.delay(post_id=post.id, old_rating=old_rating, rating=rating)
            post_rating.rating = rating
            post_rating.save()

        users_rating = rating

    context = {
        "post": post,
        "users_rating": users_rating,
    }

    return shortcuts.render(request, "post/blocks/post_rate.html", context)

blog/templates/user/blocks/modal_user_bio_update.html
<div
    class="modal fade"
    id="modal_user_bio_update"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    tabindex="-1"
    aria-labelledby="modal_user_bio_update"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_user_bio_update_label">
                    Edit "About me":
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form
                method="POST"
                class="was-validated"
                hx-post="{% url 'user_bio_update' %}"
                hx-target="#user_profile_bio"
                swap="outerHTML"

            >
                {% csrf_token %}

                <div class="modal-body">
                    <textarea
                        class="form-control is-invalid"
                        id="id_bio"
                        name="bio"
                        rows="5"
                        placeholder="User bio"
                    >{% if user_profile.bio %}{{ user_profile.bio }}{% endif %}</textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

blog/templates/user/blocks/modal_user_email_update.html
<div
    class="modal fade"
    id="modal_user_email_update"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    tabindex="-1"
    aria-labelledby="modal_user_email_update"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_user_email_update_label">
                    Edit "Email":
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form
                method="POST"
                class="was-validated"
                hx-post="{% url 'user_email_update' %}"
                hx-target="#user_profile_email"
                swap="outerHTML"

            >
                {% csrf_token %}

                <div class="modal-body">

                    <div class="form-floating mt-2">
                        <input
                            name="email"
                            id="email"
                            type="email"
                            class="form-control"
                            placeholder="name@example.com"
                            value="{{ user_profile.user.email }}"
                            required>
                        <label for="floatingInput">Email address</label>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

blog/templates/user/blocks/modal_user_names_update.html
<div
    class="modal fade"
    id="modal_user_names_update"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    tabindex="-1"
    aria-labelledby="modal_user_names_update"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_user_names_update_label">
                    Edit "Names":
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form
                method="POST"
                class="was-validated"
                hx-post="{% url 'user_names_update' %}"
                hx-target="#user_profile_names"
                swap="outerHTML"

            >
                {% csrf_token %}

                <div class="modal-body">

                    <div class="form-floating mt-2">
                        <input
                            name="first_name"
                            id="first_name"
                            type="first_name"
                            class="form-control"
                            placeholder="First name"
                            value="{{ user_profile.user.first_name }}"
                        >
                        <label for="floatingInput">First name</label>
                    </div>

                    <div class="form-floating mt-2">
                        <input
                            name="last_name"
                            id="last_name"
                            type="last_name"
                            class="form-control"
                            placeholder="Last name"
                            value="{{ user_profile.user.last_name }}"
                            >
                        <label for="floatingInput">Last name</label>
                    </div>

                    <div class="form-floating mt-2">
                        <input
                            name="username"
                            id="username"
                            type="username"
                            class="form-control"
                            placeholder="Username"
                            value="{{ user_profile.user.username }}"
                            required>
                        <label for="floatingInput">Username</label>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

blog/templates/user/blocks/modal_user_password_update.html
<div
    class="modal fade"
    id="modal_user_password_update"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    tabindex="-1"
    aria-labelledby="modal_user_email_update"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_user_email_update_label">
                    Edit "Password":
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form
                method="POST"
                action="{% url 'user_password_update' %}"
            >

                {% csrf_token %}

                <div class="modal-body">

                    <div class="form-floating mt-2">
                        <input
                            name="old_password"
                            id="old_password"
                            type="password"
                            class="form-control"
                            placeholder="Old password" required>
                        <label for="old_password">Old password</label>
                    </div>

                    <div class="form-floating mt-2">
                        <input
                            name="new_password1"
                            id="new_password1"
                            type="password"
                            class="form-control"
                            placeholder="New password" required>
                        <label for="new_password1">New password</label>
                    </div>

                    <div class="form-floating mt-2">
                        <input
                            name="new_password2"
                            id="new_password2"
                            type="password"
                            class="form-control"
                            placeholder="Repeat new password" required>
                        <label for="new_password2">Password confirmation</label>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

blog/templates/user/blocks/user_profile_bio.html
<div id="user_profile_bio">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">About me:</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    {% if user_profile.bio %}
                        {{ user_profile.bio }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            <tr>
        </tbody>
    </table>

    {% if user_profile.user == request.user %}
        <div class="d-grid gap-4 d-md-flex justify-content-md-end">
            <a
                class="btn btn-sm btn-outline-secondary"
                type="button"
                data-bs-toggle="modal"
                data-bs-target="#modal_user_bio_update"
            >
                Edit bio
            </a>
        </div>
    {% include 'user/blocks/modal_user_bio_update.html' %}

    {% endif %}

</div>

blog/templates/user/blocks/user_profile_email.html
<div id="user_profile_email">
    {% if user_profile.user == request.user %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">E-mail</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        {{ user_profile.user.email }}
                    </td>
                <tr>
            </tbody>
        </table>

        <div class="d-grid gap-4 d-md-flex justify-content-md-end">
            <div class="btn-group" role="group" aria-label="Basic outlined example">
                <a
                    class="btn btn-sm btn-outline-secondary"
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#modal_user_email_update"
                >
                    Edit email
                </a>

                <a
                    class="btn btn-sm btn-outline-secondary"
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#modal_user_password_update"
                >
                    Edit password
                </a>
            </div>
        </div>

        {% include 'user/blocks/modal_user_email_update.html' %}
        {% include 'user/blocks/modal_user_password_update.html' %}

    {% endif %}
</div>

blog/templates/user/blocks/user_profile_names.html
<div id="user_profile_names">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Username</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    {% if user_profile.user.first_name %}
                        {{ user_profile.user.first_name }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>
                    {% if user_profile.user.last_name %}
                        {{ user_profile.user.last_name }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>{{ user_profile.user.username }}</td>
            <tr>
        </tbody>
    </table>
    <div class="d-grid gap-4 d-md-flex justify-content-md-end">
        {% if user_profile.user == request.user %}

            <div class="d-grid gap-4 d-md-flex justify-content-md-end">
                <a
                    class="btn btn-sm btn-outline-secondary"
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#modal_user_names_update"
                >
                    Edit names
                </a>
            </div>
            {% include 'user/blocks/modal_user_names_update.html' %}

        {% endif %}
    </div>
</div>

blog/templates/user/blocks/user_subscribed.html
{% if subscribed.count > 0 %}
<div id="subscribed">
    <h3 class="mb-3">
        {% if not user_profile.user.first_name and not user_profile.user.last_name %}
            {{ user_profile.user.username }}'s subscribed ({{ subscribed.count }}):
        {% else %}
            {{ user_profile.user.first_name }} {{ user_profile.user.last_name }} ({{ user_profile.user.username }}) subscribed ({{ subscribed.count }}):
        {% endif %}
    </h3>
    <p>
    {% for subscriber in subscribed %}
        <a
            class="link-body-emphasis link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
            href="{% url 'user_profile' user_id=subscriber.subscribed_to.user.id %}"
        >
            {% if not subscriber.subscribed_to.user.first_name and not subscriber.subscribed_to.user.last_name %}
                {{ subscriber.subscribed_to.user.username }}
            {% else %}
                {{ subscriber.subscribed_to.user.first_name }} {{ subscriber.subscribed_to.user.last_name }} ({{ subscriber.subscribed_to.user.username }})
            {% endif %}
        </a>,
    {% endfor %}
    </p>
</div>
{% endif %}